### PR TITLE
Pass API base url directly

### PR DESCRIPTION
**Pull request by dyron**
A more future proof API environment implementation

### CODE REVIEW

**Comment by yujiberra** [comment]
@dyron 
Thanks for this!

It's certainly problematic that the SDK as it stands doesn't support the `eu` environment.

For a breaking change like this I want to consult the lead maintainer of this project, but unfortunately he is out of the office for a prolonged period so it may be a while until we can make a decision on this.

If it looks like that'll take a long time I will at least push an update to add support for `eu` using the existing `environment` property.

**Comment by dyron** [comment]
Alright, i'll had an implementation for EU, but thought this have to change every time Piano introduce a new environment.

In the meantime we'll go with our fork, but will be happy if this get merged sometime.

**Comment by yujiberra** [comment]
@dyron 
> Alright, i'll had an implementation for EU, but thought this have to change every time Piano introduce a new environment.

This is a fair point, though it might not be much of an issue if new environments aren't introduced too frequently. I'll let you know once we reach a conclusion!

Also, I realize you might be using your fork for other reasons as well, but as promised, here's a new release with support for `eu`: https://github.com/kodansha/piano-sdk-for-nodejs/releases/tag/v0.11.0

**Comment by yujiberra** [comment]
@dyron 
As mentioned before, we've added support for the `eu` region, and we're not convinced that regions will be added so frequently that allowing users to specify arbitrary base URLs will be of great benefit. (Whereas, conversely, right now we have the convenience of being able to easily specify the region with codes like `eu` and `sandbox`.)

Thanks for the contribution though, and for bringing the lack of `eu` region support to our attention!

**Pull request closed without merging**
